name = "webrtsee"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_classes = ["Room"]
